/**
 * Worlds are data, not image content — the same choice the Docker image makes
 * by bind-mounting ./worlds read-only. The player fetches
 * `worlds/index.json`, `worlds/status.json` and one era journal per world at
 * runtime, so a dev server, a preview or a bare `dist/` served statically must
 * carry them too. Without this plugin those fetches fall through to the SPA's
 * index.html fallback and the reader shows MONDE NON SERVI.
 *
 * The source of truth is whatever the machine living these worlds holds in
 * ./worlds (regenerated by `npm run index-worlds`); nothing is copied into the
 * repository and no existing file is overwritten outside dist/.
 *
 *   - `vite` / `player:dev`: middleware serves the files live from ./worlds.
 *   - `vite build` / `player:build`: closeBundle copies worlds/ into dist/,
 *     after publicDir (reports/) has been copied.
 */
import { cpSync, existsSync, readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import vue from "@vitejs/plugin-vue";
import { join, resolve } from "node:path";
import { defineConfig, type Plugin } from "vite";

/** The repo root two levels up — ./worlds lives next to package.json. */
const ROOT = fileURLToPath(new URL("../..", import.meta.url));
const WORLDS = resolve(ROOT, "worlds");

function copyWorldsPlugin(): Plugin {
  const plugin: Plugin = {
    name: "serve-worlds",
    // No `apply` gate here: configureServer only runs under `vite serve` and
    // closeBundle only under `vite build`, so one plugin covers both modes.
    configureServer(server) {
      // Live data, like the nginx mount: no-cache, straight from disk.
      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? "").split("?")[0];
        if (!url.startsWith("/worlds/") || !url.endsWith(".json")) return next();
        const rel = decodeURIComponent(url.slice("/worlds/".length));
        const full = resolve(WORLDS, rel);
        if (!full.startsWith(WORLDS) || !existsSync(full) || !statSync(full).isFile()) {
          return next();
        }
        res.setHeader("Content-Type", "application/json; charset=utf-8");
        res.setHeader("Cache-Control", "no-cache");
        res.end(readFileSync(full));
      });
    },
    closeBundle() {
      if (!existsSync(join(WORLDS, "index.json"))) {
        console.warn("[serve-worlds] worlds/index.json absent — lancez `npm run index-worlds`.");
        return;
      }
      cpSync(WORLDS, resolve(ROOT, "apps/player/dist/worlds"), { recursive: true });
      console.log("[serve-worlds] worlds/ copié dans dist/worlds.");
    },
  };
  return plugin;
}

export default defineConfig({
  plugins: [vue(), copyWorldsPlugin()],
  base: "./",
  resolve: {
    alias: {
      "@abs/contracts": fileURLToPath(new URL("../../packages/contracts/src/index.ts", import.meta.url)),
      // The player recomputes a world from its journal using the very code
      // that lived it, rather than trusting a separate rendering of events.
      "@abs/world": fileURLToPath(new URL("../../packages/world/src/index.ts", import.meta.url)),
    },
  },
});
