<script setup lang="ts">
import { computed, defineAsyncComponent, onMounted, onUnmounted, ref, watch } from "vue";
import { FACTION_IDS, type FactionId, type Replay } from "@abs/contracts";
import BattleGrid from "./components/BattleGrid.vue";
import EventLog from "./components/EventLog.vue";
import GeneralPanel from "./components/GeneralPanel.vue";
import ReportPanel from "./components/ReportPanel.vue";
import FogView from "./components/FogView.vue";
import { JournalSchema, WORLD_VERSION, worldVersionOf, type Journal } from "@abs/world";
import type { PublishedLearningCurve } from "./components/LearningCurve.vue";
import { alliesOfAt, knowledgeOf } from "./fog";
import { createRequestGuard } from "./request-guard";
import { fetchReplay, parseReplay, replayUrlFromSearch } from "./replay-loading";
// Three.js is ~400 KB. The card requires the 2D mode to stay performant, so a
// reader who never opens the 3D view never downloads it.
const Battle3D = defineAsyncComponent(() => import("./components/Battle3D.vue"));
import { BattleAudio } from "./three/audio";

const replay = ref<Replay | null>(null);
const error = ref<string | null>(null);
/** 0 is the deployment; 1..n is the state after turn n. */
const index = ref(0);
const playing = ref(false);
const speed = ref(1);
const highlight = ref<string | null>(null);

const SPEEDS = [0.5, 1, 2, 4];
const BASE_MS = 1100;

/** 2D stays the default and stays complete; 3D is an alternative view. */
const view3d = ref(false);

/**
 * Whose eyes we are reading through. Null is the omniscient view, which shows
 * more than any general ever saw — useful, but not what the battle was like.
 */
const fogFaction = ref<FactionId | null>(null);
const fogAllies = computed(() =>
  fogFaction.value && replay.value ? alliesOfAt(replay.value, fogFaction.value, index.value) : [],
);
const fogKnowledge = computed(() =>
  fogFaction.value && replay.value ? knowledgeOf(replay.value, fogFaction.value, index.value) : null,
);
const fogHidden = computed(() => {
  const k = fogKnowledge.value;
  return k && current.value ? current.value.squads.filter((s) => !k.visible.has(s.id)).length : 0;
});

/** Catalogue of replays this deployment serves, newest first. */
interface CatalogueEntry {
  path: string;
  battleId: string;
  ruleset: string;
  turns: number;
  outcome: string;
  winner: string | null;
  hasReports: boolean;
}
const catalogue = ref<CatalogueEntry[]>([]);

/**
 * Battles and worlds are two ways of watching the same models, not two apps.
 * A battle is a match with an end; a world is a place that keeps going. The
 * chronicle only appears when a deployment actually serves a world.
 */
type Mode = "battle" | "world" | "reports" | "rules";
const mode = ref<Mode>("world");

interface WorldEntry {
  path: string;
  world: string;
  era: number;
  livedTo: number;
  rulings: number;
  alive: number;
  over: boolean;
  survivor: string | null;
  /** Optional static report generated by `npm run learning-curve`. */
  learningCurvePath?: string;
}
const worlds = ref<WorldEntry[]>([]);
const activeWorld = computed(() => worlds.value.find((world) => world.path === worldPath.value) ?? worlds.value[0] ?? null);
const livingCivs = computed(() => activeWorld.value?.alive ?? journal.value?.origin.civs.filter((civ) => civ.fellOnTick === null).length ?? null);
const lastAdvance = computed(() => {
  if (!tendStatus.value || (activeWorld.value && tendStatus.value.world !== activeWorld.value.world)) return "dernière avancée inconnue";
  const date = Date.parse(tendStatus.value.ranAt);
  if (Number.isNaN(date)) return "dernière avancée inconnue";
  return `${tendStatus.value.ok ? "dernière avancée" : "avancée interrompue"} le ${new Date(date).toLocaleDateString("fr-FR", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })}`;
});
/**
 * Worlds and battles keep their own error.
 *
 * They used to share one, so a missing replay file shouted over a perfectly
 * clear message about an archived world — a reader following a permalink was
 * told about a battle they had not asked for. Two independent things deserve
 * two independent failures.
 */
const worldError = ref<string | null>(null);
const worldsLoading = ref(true);
const worldLoading = ref(false);
/** How the machine tending these worlds last fared. Absent when nobody tends them. */
const tendStatus = ref<{ ranAt: string; world: string; ok: boolean; years: number; error: string | null } | null>(null);
const worldPath = ref<string>("");
const journal = ref<Journal | null>(null);
const learningCurves = ref<PublishedLearningCurve[]>([]);
const worldRequests = createRequestGuard();
// Three.js is lazy for weight; the chronicle is lazy for the same reason —
// a reader who only watches battles never loads the world engine.
const Chronicle = defineAsyncComponent(() => import("./components/Chronicle.vue"));
const Reports = defineAsyncComponent(() => import("./components/Reports.vue"));
const Rules = defineAsyncComponent(() => import("./components/Rules.vue"));

async function loadWorlds() {
  try {
    const res = await fetch("worlds/index.json");
    if (res.ok) worlds.value = await res.json();
  } catch {
    // No worlds served here. The chronicle tab simply does not appear.
  }
  try {
    const res = await fetch("worlds/status.json");
    if (res.ok) tendStatus.value = await res.json();
  } catch {
    // Nobody tends these worlds automatically; the chronicle says nothing.
  } finally {
    worldsLoading.value = false;
  }
}

async function openWorld(path: string) {
  const request = worldRequests.begin();
  worldPath.value = path;
  worldLoading.value = true;
  learningCurves.value = [];
  try {
    const res = await fetch(path);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const raw = await res.json();
    if (!worldRequests.isCurrent(request)) return;

    // An archived world is not a broken file, and saying "Invalid literal
    // value, expected w3" to a reader who followed a permalink is telling them
    // about zod instead of about the world. The rules a world lived under are
    // part of what it was.
    const version = worldVersionOf(raw);
    if (version !== WORLD_VERSION) {
      journal.value = null;
      worldError.value =
        `Ce monde a vécu sous les règles ${version ?? "inconnues"}, et le moteur tourne aujourd'hui en ${WORLD_VERSION}. ` +
        `Il est conservé comme archive : le rejouer sous les règles d'aujourd'hui montrerait des années qu'il n'a jamais vécues.`;
      return;
    }

    const parsed = JournalSchema.safeParse(raw);
    if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? "journal invalide");
    journal.value = parsed.data;
    worldError.value = null;

    const reportPath = worlds.value.find((world) => world.path === path)?.learningCurvePath
      ?? (path.endsWith(".json") ? path.replace(/\.json$/, ".learning.json") : `${path}.learning.json`);
    try {
      const reportResponse = await fetch(reportPath);
      if (!worldRequests.isCurrent(request)) return;
      if (reportResponse.ok) {
        const report = await reportResponse.json();
        if (!worldRequests.isCurrent(request)) return;
        const journalName = path.split("/").at(-1);
        // Source buttons can only seek honestly when every metric observation
        // belongs to the journal currently on screen.
        if (isLearningCurveReport(report) && report.sources.length === 1 && report.sources[0] === journalName) {
          learningCurves.value = report.curves;
        }
      }
    } catch {
      // The world remains readable; the profile states that metric data is insufficient.
    }
  } catch (err) {
    if (!worldRequests.isCurrent(request)) return;
    journal.value = null;
    worldError.value = `Impossible de charger ${path} — ${(err as Error).message}`;
  } finally {
    if (worldRequests.isCurrent(request)) worldLoading.value = false;
  }
}

const SIGNALS = new Set(["ADAPTATION_OBSERVED", "NO_EVIDENCE", "INSUFFICIENT_DATA", "UNRANKED"]);
const SERIES_KEYS = ["consequenceRecognition", "errorCorrection", "doctrineCoherence", "narrativeFidelity"];
const isRecord = (value: unknown): value is Record<string, unknown> => !!value && typeof value === "object" && !Array.isArray(value);
const isNumber = (value: unknown) => typeof value === "number" && Number.isFinite(value);
const isNullableNumber = (value: unknown) => value === null || isNumber(value);
const isStringArray = (value: unknown): value is string[] => Array.isArray(value) && value.every((item) => typeof item === "string");
const isNumberArray = (value: unknown): value is number[] => Array.isArray(value) && value.every(isNumber);
const isObservationEvent = (value: unknown) => isRecord(value)
  && typeof value.id === "string"
  && isNumber(value.tick)
  && typeof value.kind === "string"
  && typeof value.detail === "string";
const isMetricPoint = (value: unknown) => {
  if (!isRecord(value) || !isRecord(value.window) || !isRecord(value.uncertainty)) return false;
  return typeof value.metric === "string"
    && isNumber(value.window.startTick) && isNumber(value.window.endTick)
    && isNumber(value.numerator) && isNumber(value.denominator) && isNullableNumber(value.value)
    && isNumber(value.sampleCount) && isNullableNumber(value.serviceRate) && isNullableNumber(value.fallbackRate)
    && isNumber(value.unknownServiceCount) && value.uncertainty.method === "WILSON_95"
    && isNullableNumber(value.uncertainty.lower) && isNullableNumber(value.uncertainty.upper)
    && isNumber(value.uncertainty.seedCount) && isNumber(value.uncertainty.runCount)
    && isStringArray(value.eventSourceIds);
};
const isPublishedCurve = (value: unknown): value is PublishedLearningCurve => {
  if (!isRecord(value) || !isRecord(value.series) || !isRecord(value.options)) return false;
  return (value.modelId === null || typeof value.modelId === "string")
    && isStringArray(value.runIds) && isNumberArray(value.seeds)
    && (value.pairedRunKey === null || typeof value.pairedRunKey === "string")
    && isNumber(value.sampleCount) && isNullableNumber(value.serviceRate) && isNullableNumber(value.fallbackRate)
    && isNumber(value.unknownServiceCount) && Array.isArray(value.eventSources) && value.eventSources.every(isObservationEvent)
    && isStringArray(value.unrankedReasons) && typeof value.classification === "string" && SIGNALS.has(value.classification)
    && SERIES_KEYS.every((key) => Array.isArray(value.series[key]) && value.series[key].every(isMetricPoint));
};

function isLearningCurveReport(value: unknown): value is { protocol: "aevum-learning-curve-v1"; sources: string[]; curves: PublishedLearningCurve[] } {
  return isRecord(value)
    && value.protocol === "aevum-learning-curve-v1"
    && isStringArray(value.sources)
    && Array.isArray(value.curves)
    && value.curves.every(isPublishedCurve);
}
const currentPath = ref<string>("");
/** A turn requested by URL, applied once the replay's length is known. */
let pendingTurn = 0;
const audio = new BattleAudio();
const soundOn = ref(false);

const turnCount = computed(() => replay.value?.turns.length ?? 0);
const current = computed(() => {
  if (!replay.value) return null;
  return index.value === 0 ? replay.value.initialState : replay.value.turns[index.value - 1]!.stateAfter;
});
const currentTurn = computed(() => (index.value === 0 ? null : replay.value!.turns[index.value - 1]!));
const atEnd = computed(() => index.value >= turnCount.value);

function load(raw: unknown, source: string) {
  const parsed = parseReplay(raw);
  if (!parsed.success) {
    error.value = `Replay invalide (${source}) : ${parsed.error.issues[0]?.path.join(".")} — ${parsed.error.issues[0]?.message}`;
    return;
  }
  replay.value = parsed.data;
  error.value = null;
  // A turn asked for in the URL is honoured once the replay is known to be
  // long enough; otherwise we open at the deployment.
  index.value = pendingTurn > 0 ? Math.min(pendingTurn, parsed.data.turns.length) : 0;
  pendingTurn = 0;
}

async function loadFromUrl(url: string) {
  try {
    load(await fetchReplay(url), url);
  } catch (err) {
    error.value = `Impossible de charger ${url} — ${(err as Error).message}. Choisissez un fichier de replay ci-dessous.`;
  }
}

async function onFile(event: Event) {
  const file = (event.target as HTMLInputElement).files?.[0];
  if (!file) return;
  try {
    load(JSON.parse(await file.text()), file.name);
  } catch (err) {
    error.value = `Fichier illisible — ${(err as Error).message}`;
  }
}

const step = (delta: number) => {
  index.value = Math.min(turnCount.value, Math.max(0, index.value + delta));
  if (atEnd.value) playing.value = false;
};

function onKey(e: KeyboardEvent) {
  if (e.target instanceof HTMLInputElement || mode.value !== "battle") return;
  const actions: Record<string, () => void> = {
    ArrowRight: () => step(1),
    ArrowLeft: () => step(-1),
    Home: () => (index.value = 0),
    End: () => (index.value = turnCount.value),
    " ": () => (playing.value = !playing.value),
  };
  const action = actions[e.key];
  if (!action) return;
  e.preventDefault();
  action();
}

let timer: number | undefined;
watch([playing, speed], () => {
  clearInterval(timer);
  if (!playing.value) return;
  timer = window.setInterval(() => (atEnd.value ? (playing.value = false) : step(1)), BASE_MS / speed.value);
});

async function loadCatalogue() {
  try {
    const res = await fetch("replays/index.json");
    if (res.ok) catalogue.value = await res.json();
  } catch {
    // No catalogue is fine: the picker simply does not appear.
  }
}

function pick(path: string) {
  currentPath.value = path;
  // Keep the URL honest, so a chosen replay can be shared or reloaded.
  const url = new URL(location.href);
  url.searchParams.set("replay", `replays/${path}`);
  history.replaceState(null, "", url);
  loadFromUrl(`replays/${path}`);
}

// The point of view belongs in the URL too: "look at turn 7 through amber's
// eyes" is exactly the kind of thing one person sends another.
watch([fogFaction, index, view3d], ([faction, turn, is3d]) => {
  const url = new URL(location.href);
  if (faction) url.searchParams.set("view", faction as string);
  else url.searchParams.delete("view");
  if ((turn as number) > 0) url.searchParams.set("turn", String(turn));
  else url.searchParams.delete("turn");
  if (is3d) url.searchParams.set("mode", "3d");
  else url.searchParams.delete("mode");
  history.replaceState(null, "", url);
});

watch([mode, worldPath], ([m, path]) => {
  const url = new URL(location.href);
  if (m === "world" && path) url.searchParams.set("world", path as string);
  else url.searchParams.delete("world");
  if (m === "reports") url.searchParams.set("mode", "a-propos");
  else if (m === "rules") url.searchParams.set("mode", "regles");
  else if (["rapports", "a-propos", "regles"].includes(url.searchParams.get("mode") ?? "")) url.searchParams.delete("mode");
  history.replaceState(null, "", url);
});

onMounted(async () => {
  window.addEventListener("keydown", onKey);
  await Promise.all([loadCatalogue(), loadWorlds()]);

  const wanted = new URLSearchParams(location.search).get("world");
  if (wanted || worlds.value.length > 0) {
    const first = wanted ?? worlds.value[0]!.path;
    await openWorld(first);
    if (wanted) mode.value = "world";
  }

  const params = new URLSearchParams(location.search);
  if (params.get("mode") === "3d") view3d.value = true;
  if (params.get("mode") === "regles") mode.value = "rules";
  else if (["rapports", "a-propos"].includes(params.get("mode") ?? "") || params.get("rapport")) mode.value = "reports";
  else if (params.get("replay") || params.get("turn")) mode.value = "battle";
  const view = params.get("view");
  if (view && (FACTION_IDS as readonly string[]).includes(view)) fogFaction.value = view as FactionId;
  const turn = Number(params.get("turn"));
  if (Number.isInteger(turn) && turn > 0) pendingTurn = turn;

  const requested = replayUrlFromSearch(location.search);
  if (requested) {
    currentPath.value = requested.replace(/^replays\//, "");
    loadFromUrl(requested);
    return;
  }
  // Default to the newest battle rather than a hardcoded filename, so adding a
  // replay does not leave the landing page showing an old one.
  const first = catalogue.value[0]?.path ?? "reference.json";
  currentPath.value = first;
  loadFromUrl(`replays/${first}`);
});
// Sound follows the turn being displayed, so scrubbing backwards is silent
// rather than replaying old noise.
watch(index, (next, previous) => {
  if (!soundOn.value || next <= previous || !replay.value) return;
  audio.playTurn(replay.value.turns[next - 1]?.events ?? []);
});

onUnmounted(() => {
  window.removeEventListener("keydown", onKey);
  clearInterval(timer);
  audio.dispose();
});
</script>

<template>
  <div class="app">
    <header class="mast">
      <div class="brand">
        <h1>Aevum — Chronique des mondes</h1>
        <p>Un monde gouverné par quatre modèles, rejouable à l'identique</p>
      </div>

      <p v-if="mode === 'world'" class="world-signal mono">
        <span>{{ activeWorld?.world ?? "monde non servi" }}</span>
        <span v-if="journal">ère {{ journal.era }} · an {{ journal.livedTo }} · {{ livingCivs ?? 0 }} civilisations vivantes</span>
        <span>{{ lastAdvance }}</span>
      </p>

      <nav class="modeswitch" aria-label="Navigation principale">
        <button type="button" :aria-current="mode === 'world' ? 'page' : undefined" @click="mode = 'world'">Chronique</button>
        <button type="button" :aria-current="mode === 'battle' ? 'page' : undefined" @click="mode = 'battle'">Archives</button>
        <button type="button" :aria-current="mode === 'rules' ? 'page' : undefined" @click="mode = 'rules'">Règles</button>
        <button type="button" :aria-current="mode === 'reports' ? 'page' : undefined" @click="mode = 'reports'">À propos</button>
      </nav>
    </header>

    <p class="section-deck mono">
      {{
        mode === "battle"
          ? "ARCHIVES · batailles tactiques v1 et v2, conservées sous leurs règles"
          : mode === "world"
            ? "CHRONIQUE · les dirigeants décident aux points d'arbitrage ; le moteur résout toutes les autres années"
            : mode === "rules"
              ? "RÈGLES · ce qu'un dirigeant décide et ce que le moteur tranche"
              : "À PROPOS · méthode, limites, mesures et rapports"
      }}
    </p>
      <label v-if="mode === 'world' && worlds.length > 1" class="picker-inline mono">
        <span class="visually-hidden">Monde affiché</span>
        <select :value="worldPath" @change="openWorld(($event.target as HTMLSelectElement).value)">
          <option v-for="w in worlds" :key="w.path" :value="w.path">
            {{ w.world }} · ère {{ w.era }} · {{ w.livedTo }} ans ·
            {{ w.over ? (w.survivor ? `${w.survivor} seule` : "éteint") : `${w.alive} vivantes` }}
          </option>
        </select>
      </label>

      <label v-if="mode === 'battle' && catalogue.length > 1" class="picker-inline mono">
        <span class="visually-hidden">Bataille affichée</span>
        <select :value="currentPath" @change="pick(($event.target as HTMLSelectElement).value)">
          <option v-for="entry in catalogue" :key="entry.path" :value="entry.path">
            {{ entry.ruleset }} · {{ entry.turns }}t · {{ entry.outcome }}{{ entry.hasReports ? " · rapports" : "" }} —
            {{ entry.path }}
          </option>
        </select>
      </label>

      <dl v-if="mode === 'battle' && replay" class="summary mono">
        <div>
          <dt>issue</dt>
          <dd>
            {{ replay.outcome.kind }}{{
              replay.outcome.winner
                ? ` · ${replay.outcome.winner}`
                : replay.outcome.winners?.length
                  ? ` · ${replay.outcome.winners.join(" + ")}`
                  : ""
            }}
          </dd>
        </div>
        <div><dt>tours</dt><dd>{{ turnCount }}</dd></div>
        <div><dt>règles</dt><dd>{{ replay.manifest.rulesetVersion }}</dd></div>
        <div><dt>graine</dt><dd>{{ replay.manifest.config.seed }}</dd></div>
      </dl>

    <p v-if="mode === 'battle' && error" class="card error" role="alert">{{ error }}</p>
    <p v-if="mode === 'world' && worldError" class="card error" role="alert">{{ worldError }}</p>

    <p v-if="mode === 'world' && (worldsLoading || worldLoading)" class="loading-state mono" role="status">
      Recomposition du monde
    </p>

    <Chronicle v-if="mode === 'world' && journal" :journal="journal" :status="tendStatus" :learning-curves="learningCurves" />

    <main v-if="mode === 'reports'" class="about">
      <header class="about-intro">
        <p class="eyebrow mono">À propos</p>
        <h2>Une chronique vérifiable, pas un verdict sur les modèles.</h2>
        <p>
          Le journal conserve leurs décisions. Le moteur déterministe recompose ici chaque année, sans rappeler
          aucun modèle. Les rapports ci-dessous publient aussi les limites et les mesures qui ont contredit nos hypothèses.
        </p>
      </header>
      <Reports />
    </main>

    <Rules v-if="mode === 'rules'" />

    <p v-if="mode === 'world' && !journal && !worldError && !worldsLoading && !worldLoading" class="card picker">
      Aucun journal de monde n'est servi ici. La méthode, les règles et les archives restent consultables.
    </p>

    <p v-if="mode === 'battle' && !replay" class="card picker">
      <label for="file">Charger un fichier de replay</label>
      <input id="file" type="file" accept="application/json" @change="onFile" />
    </p>

    <p v-if="mode === 'battle'" class="card archive-note">
      Les règles <strong>v1</strong> et <strong>v2</strong> sont gelées : quatre modèles commandaient
      des escouades sur une grille, et c'est de là que ce projet est parti. Le monde continu leur a
      succédé parce qu'il répond mieux à la même question, et pour bien moins d'appels — 98 % de
      service contre moins de 50 %. Ces batailles restent jouables et lisibles telles quelles.
    </p>

    <main v-if="mode === 'battle' && replay && current" class="layout">
      <section class="board">
        <div class="viewswitch" role="group" aria-label="Mode d'affichage">
          <button type="button" class="mono" :aria-pressed="!view3d" @click="view3d = false">Grille 2D</button>
          <button type="button" class="mono" :aria-pressed="view3d" @click="view3d = true">Vue 3D</button>
          <button
            type="button"
            class="mono"
            :aria-pressed="soundOn"
            :title="soundOn ? 'Couper le son' : 'Activer le son (synthétisé, aucun fichier)'"
            @click="soundOn = !soundOn; audio.enabled = soundOn"
          >
            {{ soundOn ? "Son activé" : "Son coupé" }}
          </button>
        </div>

        <FogView
          v-model="fogFaction"
          :knowledge="fogKnowledge"
          :allies="fogAllies"
          :hidden="fogHidden"
          :turn-index="index"
        />

        <Battle3D
          v-if="view3d"
          :state="current"
          :grid-size="replay.manifest.config.gridSize"
          :alliance-pairs="currentTurn?.alliances?.pairs ?? []"
        />
        <BattleGrid
          v-else
          :state="current"
          :grid-size="replay.manifest.config.gridSize"
          :highlight="highlight"
          :alliance-pairs="currentTurn?.alliances?.pairs ?? []"
          :visible="fogKnowledge?.visible ?? null"
          :remembered="fogKnowledge?.remembered ?? null"
        />

        <p v-if="currentTurn?.alliances?.pairs?.length" class="alliances mono">
          Alliances en vigueur :
          {{ currentTurn.alliances.pairs.map((p) => p.replace("|", " + ")).join(" · ") }}
        </p>
        <p v-if="currentTurn?.alliances?.surrendered?.length" class="alliances mono surrender">
          Ont capitulé : {{ currentTurn.alliances.surrendered.join(", ") }}
        </p>

        <div class="controls card">
          <div class="buttons">
            <!-- Text labels rather than transport glyphs: ▶ and ⏮ render as
                 colour emoji on some platforms, which the design system rules
                 out for icons. -->
            <button type="button" class="mono" :disabled="index === 0" aria-label="Revenir au déploiement" @click="index = 0">
              Début
            </button>
            <button type="button" class="mono" :disabled="index === 0" aria-label="Tour précédent" @click="step(-1)">
              Préc.
            </button>
            <button
              type="button"
              class="play"
              :aria-label="playing ? 'Mettre en pause' : 'Lancer la lecture'"
              :disabled="atEnd"
              @click="playing = !playing"
            >
              {{ playing ? "Pause" : "Lecture" }}
            </button>
            <button type="button" class="mono" :disabled="atEnd" aria-label="Tour suivant" @click="step(1)">Suiv.</button>
            <button type="button" class="mono" :disabled="atEnd" aria-label="Aller à la fin" @click="index = turnCount">
              Fin
            </button>
          </div>

          <label class="scrub">
            <span class="visually-hidden">Tour affiché</span>
            <input v-model.number="index" type="range" min="0" :max="turnCount" step="1" />
            <output class="mono">{{ index === 0 ? "déploiement" : `tour ${index} / ${turnCount}` }}</output>
          </label>

          <div class="speeds" role="group" aria-label="Vitesse de lecture">
            <button
              v-for="s in SPEEDS"
              :key="s"
              type="button"
              class="speed mono"
              :aria-pressed="speed === s"
              @click="speed = s"
            >
              {{ s }}×
            </button>
          </div>
        </div>

        <p class="hint mono">Clavier : ← → tour à tour · Espace lecture/pause · Début / Fin</p>
        <p class="live" role="status" aria-live="polite">
          {{ index === 0 ? "Déploiement initial" : `Tour ${index} sur ${turnCount}` }}, {{ current.squads.length }} escouades en vie.
        </p>
      </section>

      <aside class="side">
        <GeneralPanel v-if="currentTurn" :decisions="currentTurn.decisions" :state="current" />
        <p v-else class="card empty">
          Déploiement initial. Avancez d'un tour pour lire les ordres et la justification de chaque général.
        </p>
        <EventLog :events="currentTurn?.events ?? []" @focus-squad="highlight = $event" />
      </aside>
    </main>

    <ReportPanel
      v-if="replay?.reports?.length"
      :reports="replay.reports"
      :audits="replay.audits"
      @go-to-turn="index = Math.min(turnCount, Math.max(0, $event))"
    />

    <footer v-if="replay" class="foot mono">
      {{ replay.outcome.reason }} · replay {{ replay.manifest.battleId }} · contrats {{ replay.manifest.contractsVersion }}
    </footer>
  </div>
</template>

<style scoped>
.app {
  max-width: 1440px;
  margin: 0 auto;
  padding: 0 var(--s5) var(--s6);
  display: flex;
  flex-direction: column;
  gap: var(--s5);
}

.mast {
  min-height: 88px;
  display: flex;
  gap: var(--s5);
  align-items: center;
  justify-content: space-between;
  min-width: 0;
  border-bottom: 1px solid var(--border);
  background: var(--bg);
  position: sticky;
  top: 0;
  z-index: 20;
}

.mast > * {
  min-width: 0;
}

h1 {
  font-family: var(--display);
  font-size: clamp(22px, 2.2vw, 31px);
  font-weight: 500;
  letter-spacing: -0.025em;
}

.brand p {
  margin: 2px 0 0;
  color: var(--muted);
  font-size: 12px;
  white-space: nowrap;
}

.world-signal {
  margin: 0;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  font-size: 10px;
  line-height: 1.55;
  color: var(--muted);
  text-align: right;
}

.world-signal span:first-child {
  color: var(--fg);
  text-transform: uppercase;
  letter-spacing: 0.1em;
}

.section-deck {
  margin: calc(var(--s3) * -1) 0 0;
  color: var(--accent);
  font-size: 10px;
  letter-spacing: 0.11em;
}

.summary,
.controls dl {
  display: flex;
  flex-wrap: wrap;
  gap: var(--s4);
  margin: 0;
  font-size: 12px;
}

.summary dt {
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  font-size: 10px;
}

.summary dd {
  margin: 0;
  font-size: 14px;
}

.error {
  color: var(--crimson);
  border-color: var(--crimson);
  margin: 0;
}

/* A select sizes itself to its longest option, which pushed the header past
   the viewport at 375px — and this project's own rule is that the body never
   scrolls horizontally. Constrained on both the flex item and the control. */
.picker-inline {
  flex: 1 1 100%;
  min-width: 0;
  max-width: 100%;
}

.picker-inline select {
  width: 100%;
  font: inherit;
  font-size: 12px;
  color: var(--fg);
  background: var(--card-raised);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: var(--s2);
  min-height: 44px;
  max-width: 100%;
  cursor: pointer;
  text-overflow: ellipsis;
}

.picker {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--s3);
  margin: 0;
}

.loading-state {
  min-height: 42vh;
  display: grid;
  place-items: center;
  margin: 0;
  color: var(--muted);
  border-block: 1px solid var(--border-soft);
  font-size: 11px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

.about {
  display: flex;
  flex-direction: column;
  gap: var(--s6);
}

.about-intro {
  padding: clamp(var(--s5), 5vw, 64px) 0 var(--s5);
  border-bottom: 1px solid var(--border);
}

.about-intro .eyebrow {
  margin: 0 0 var(--s2);
  color: var(--accent);
  font-size: 11px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

.about-intro h2 {
  max-width: 20ch;
  font-family: var(--display);
  font-size: clamp(30px, 5vw, 58px);
  font-weight: 400;
  line-height: 1.02;
}

.about-intro > p:last-child {
  max-width: 68ch;
  margin: var(--s4) 0 0;
  color: var(--muted);
}

.layout {
  display: grid;
  grid-template-columns: minmax(0, 1.35fr) minmax(320px, 1fr);
  gap: var(--s4);
  align-items: start;
}

.board {
  display: flex;
  flex-direction: column;
  gap: var(--s3);
  min-width: 0;
}

.side {
  display: flex;
  flex-direction: column;
  gap: var(--s3);
  min-width: 0;
}

.controls {
  display: flex;
  flex-direction: column;
  gap: var(--s3);
}

.buttons {
  display: flex;
  flex-wrap: wrap;
  gap: var(--s2);
}

.play {
  min-width: 116px;
  font-weight: 600;
}

.scrub {
  display: flex;
  align-items: center;
  gap: var(--s3);
}

.scrub input {
  flex: 1;
  min-width: 0;
  height: 44px;
  accent-color: var(--accent);
  cursor: pointer;
}

.scrub output {
  flex: none;
  min-width: 116px;
  text-align: right;
  font-size: 12px;
  color: var(--muted);
}

.speeds {
  display: flex;
  gap: var(--s2);
}

.speed {
  flex: 1;
  font-size: 12px;
}

.viewswitch,
.modeswitch {
  display: flex;
  flex-wrap: wrap;
  gap: 2px;
}

.viewswitch button {
  font-size: 12px;
}

.modeswitch button {
  min-width: auto;
  padding: var(--s2) var(--s3);
  border-color: transparent;
  border-radius: 0;
  background: transparent;
  font-size: 13px;
}

.modeswitch button[aria-current="page"] {
  color: var(--fg);
  border-bottom-color: var(--accent);
}

.archive-note {
  margin: 0;
  font-size: 13px;
  color: var(--muted);
  max-width: 74ch;
  line-height: 1.6;
}

.archive-note strong {
  color: var(--fg);
  font-weight: 600;
}

.alliances {
  margin: 0;
  font-size: 12px;
  color: var(--verdant);
}

.alliances.surrender {
  color: var(--amber);
}

.hint,
.live {
  margin: 0;
  font-size: 11px;
  color: var(--muted);
}

.empty {
  margin: 0;
  color: var(--muted);
  font-size: 13px;
}

.foot {
  font-size: 11px;
  color: var(--muted);
  border-top: 1px solid var(--border-soft);
  padding-top: var(--s3);
}

@media (max-width: 900px) {
  .app {
    padding-inline: var(--s4);
  }

  .mast {
    position: static;
    flex-wrap: wrap;
    padding: var(--s3) 0;
    gap: var(--s3);
  }

  .world-signal {
    margin-left: auto;
  }

  .modeswitch {
    order: 3;
    width: 100%;
  }

  .modeswitch button {
    flex: 1;
  }

  .layout {
    grid-template-columns: minmax(0, 1fr);
  }
}

@media (max-width: 560px) {
  .app {
    padding-inline: var(--s3);
    gap: var(--s4);
  }

  .brand p {
    max-width: 32ch;
    white-space: normal;
  }

  .world-signal {
    width: 100%;
    align-items: flex-start;
    text-align: left;
    border-left: 1px solid var(--accent);
    padding-left: var(--s3);
  }

  .modeswitch {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
  }

  .modeswitch button {
    padding-inline: var(--s1);
    font-size: 11px;
  }
}
</style>
